name: CI

on:
  push:
    branches:
      - master
    # paths:
    #   - 'docker/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u seekwe -p ${{ secrets.DOCKER_HUB_PWD }}
      - name: Docker build latest
        run: |
          docker build -t seekwe/go-builder:latest ./docker/1.14/
          docker push seekwe/go-builder:latest
          docker build -t seekwe/go-builder:1.14 ./docker/1.14/
      - name: Docker build other
        run: |
          docker build -t seekwe/go-builder:1.11 ./docker/1.11/
          docker push seekwe/go-builder:1.11
          docker build -t seekwe/go-builder:1.14 ./docker/1.14/
          docker push seekwe/go-builder:1.14
